# Generated by Django 2.0 on 2018-06-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte', models.CharField(max_length=100)),
                ('cine', models.CharField(max_length=100)),
                ('musica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='infoadicional',
            name='nomb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicional', to='INFO.InfoBasica'),
        ),
    ]
